Repository BabsLabs/sumo_city, pull requests merged in 2020-05, with the labels that each got.

#55 52 Restructure Testing directories
  spec/features/about_spec.rb
  spec/features/footer_spec.rb
  spec/features/index_spec.rb
  spec/features/navbar_spec.rb
Labels: chore, testing

#57 31 Add SumoWiki page
  README.md
  app/assets/stylesheets/application.css
  app/controllers/terms_controller.rb
  app/javascript/components/layout/Banner.js
  app/javascript/components/layout/Navbar.js
  app/javascript/components/layout/homepage/HeroSumoWiki.js
  app/javascript/components/layout/wiki/Term.js
  app/models/term.rb
  app/views/terms/index.html.erb
  config/routes.rb
  lib/tasks/import_terms.rake
  spec/features/index_spec.rb
  spec/features/navbar_spec.rb
  spec/features/wiki_spec.rb
  spec/models/term_spec.rb
Labels: bug fix, database, enhancement, testing

#61 60 Enable SASS Styling
  README.md
  app/assets/stylesheets/application.css
  app/assets/stylesheets/layout.scss
Labels: chore, setup or configuration

#62 58 Add About page banner
  app/javascript/components/layout/About.js
  app/views/about/index.html.erb
  spec/features/about_spec.rb
Labels: chore

#63 Add stable explorer page with mapbox component
  .gitignore
  Gemfile
  Gemfile.lock
  README.md
  app/controllers/explorer_controller.rb
  app/javascript/components/layout/Navbar.js
  app/javascript/components/layout/map/Map.js
  app/views/explorer/index.html.erb
  config/application.rb
  config/routes.rb
  config/webpack/environment.js
  package-lock.json
  package.json
  spec/features/explorer_spec.rb
  spec/features/navbar_spec.rb
  yarn.lock
Labels: documentation, enhancement, research, setup or configuration, testing

#65 Move dotenv to production to work on Heroku
  Gemfile
Labels: bug fix, chore

#70 Update mapbox center to be over Tokyo Japan
  app/javascript/components/layout/map/Map.js
Labels: chore

#71 69 Fix travis.ci by switching testing to Firefox
  .travis.yml
  README.md
  spec/rails_helper.rb
Labels: bug fix, chore, documentation, setup or configuration, testing

#73 54 Add Media Queries
  app/assets/stylesheets/_breakpoints.scss
  app/assets/stylesheets/_mixins.scss
  app/assets/stylesheets/layout.scss
Labels: enhancement

#82 67 Add Color-coded Mapbox pins with titles
  README.md
  app/controllers/explorer_controller.rb
  app/javascript/components/layout/map/Map.js
  app/javascript/components/layout/map/Mapbox.js
  app/models/stable.rb
  app/views/explorer/index.html.erb
  db/data/sumocity_stable_data.csv
  db/migrate/20200513033854_create_stables.rb
  db/schema.rb
  lib/tasks/import_stables.rake
  package-lock.json
  package.json
  spec/models/stable_spec.rb
  yarn.lock
Labels: database, documentation, enhancement, testing

#90 89 light mapbox style
  app/javascript/components/layout/map/Mapbox.js
  spec/features/explorer_spec.rb
Labels: chore, enhancement

#93 92 mapbox on homepage
  app/assets/stylesheets/layout.scss
  app/controllers/index_controller.rb
  app/javascript/components/layout/homepage/HeroStableExplorer.js
  app/javascript/components/layout/map/Mapbox.js
  app/views/index/index.html.erb
  spec/features/index_spec.rb
Labels: enhancement, testing

#96 95 hompage mapbox hotfix
  app/controllers/explorer_controller.rb
  app/controllers/index_controller.rb
Labels: bug fix

#97 94 homepage links
  app/assets/stylesheets/layout.scss
  app/javascript/components/layout/homepage/HeroStableExplorer.js
  spec/features/index_spec.rb
Labels: enhancement, testing

#98 72 mobile navbar
  app/assets/stylesheets/layout.scss
  app/javascript/components/images/DemoMapboxImage.png
  app/javascript/components/layout/Footer.js
  app/javascript/components/layout/Navbar.js
  app/javascript/components/layout/homepage/HeroStableExplorer.js
  package-lock.json
  package.json
  spec/features/navbar_spec.rb
  yarn.lock
Labels: enhancement, setup or configuration, testing

#100 Update hamburger menu style to relative to keep it in navbar
  app/assets/stylesheets/layout.scss
Labels: bug fix

#101 88 Rename heroStableExplorer to heroExplorer
  app/javascript/components/layout/homepage/HeroExplorer.js
  app/views/index/index.html.erb
Labels: chore

#102 79 Explorer Marker Popups on click
  README.md
  app/javascript/components/images/SumoMarker.png
  app/javascript/components/layout/homepage/HeroExplorer.js
  app/javascript/components/layout/map/Mapbox.js
  app/views/explorer/index.html.erb
  app/views/index/index.html.erb
  package-lock.json
  package.json
  spec/features/index_spec.rb
  yarn.lock
Labels: enhancement, setup or configuration, testing

#107 106 mapbox console
  app/javascript/components/layout/map/Mapbox.js
  app/views/explorer/index.html.erb
Labels: bug fix, chore

#110 Add viewport trigger to trigger responsive css
  app/views/layouts/application.html.erb
Labels: enhancement

#113 112 Update mobile navbar display to use bubble
  app/javascript/components/layout/Navbar.js
Labels: enhancement

#114 111 Add Stable Index and Show pages
  Gemfile
  Gemfile.lock
  README.md
  app/assets/stylesheets/layout.scss
  app/controllers/stables_controller.rb
  app/javascript/components/layout/Navbar.js
  app/javascript/components/layout/map/Mapbox.js
  app/javascript/components/layout/stables/Stable.js
  app/views/stables/index.html.erb
  app/views/stables/show.html.erb
  config/routes.rb
  spec/factories.rb
  spec/features/explorer_spec.rb
  spec/features/navbar_spec.rb
  spec/features/stables/stable_index_spec.rb
  spec/features/stables/stable_show_spec.rb
  spec/rails_helper.rb
  spec/support/factory_bot.rb
Labels: documentation, enhancement, setup or configuration, testing

#120 44 118 Add Sumos
  README.md
  app/assets/stylesheets/layout.scss
  app/controllers/sumos_controller.rb
  app/javascript/components/layout/Navbar.js
  app/javascript/components/layout/sumos/Sumo.js
  app/models/stable.rb
  app/models/sumo.rb
  app/views/sumos/index.html.erb
  app/views/sumos/show.html.erb
  config/routes.rb
  db/data/sumocity_sumo_data.csv
  db/migrate/20200522164557_create_sumos.rb
  db/migrate/20200522164743_add_stable_to_sumo.rb
  db/schema.rb
  lib/tasks/import_sumos.rake
  spec/factories.rb
  spec/features/navbar_spec.rb
  spec/features/sumos/sumo_index_spec.rb
  spec/features/sumos/sumo_show_spec.rb
  spec/models/stable_spec.rb
  spec/models/sumo_spec.rb
Labels: database, documentation, enhancement, testing

#121 119 Add Top Sumos to Stable show pages
  app/assets/stylesheets/layout.scss
  app/controllers/stables_controller.rb
  app/javascript/components/layout/stables/Stable.js
  app/javascript/components/layout/stables/StableSumos.js
  app/javascript/components/layout/sumos/Sumo.js
  app/views/stables/show.html.erb
  spec/features/stables/stable_show_spec.rb
Labels: enhancement, testing

#125 122 Add link the the sumos stable page on sumo show pages
  app/controllers/sumos_controller.rb
  app/javascript/components/layout/sumos/Sumo.js
  app/views/sumos/show.html.erb
  spec/features/sumos/sumo_show_spec.rb
Labels: enhancement, testing

#126 124 Responsive Sumo Lists
  README.md
  app/javascript/components/layout/stables/StableSumos.js
  app/views/stables/show.html.erb
  spec/features/stables/stable_show_spec.rb
Labels: enhancement, testing

#128 123 render top sumo
  app/views/stables/show.html.erb
  spec/features/stables/stable_show_spec.rb
Labels: enhancement, testing

#129 116 / 117 Raketask updates
  README.md
  app/models/stable.rb
  app/models/sumo.rb
  app/models/term.rb
  db/data/sumocity_kimarite_terms.csv
  db/data/sumocity_sumo_data.csv
  db/data/sumocity_terms_data.csv
  lib/tasks/import.rake
  lib/tasks/import_stables.rake
  lib/tasks/import_sumos.rake
  lib/tasks/import_terms.rake
  spec/models/term_spec.rb
Labels: chore, documentation, enhancement, setup or configuration, testing

#134 133 Add Navbar Icons
  README.md
  app/assets/stylesheets/layout.scss
  app/javascript/components/layout/Navbar.js
  app/views/layouts/application.html.erb
  spec/features/navbar_spec.rb
Labels: enhancement, testing
